
#docker pull ubuntu

FROM ubuntu
MAINTAINER name-q<1620206666@qq.com>

CMD echo 'action is success'

#构建虚悬镜像
#docker build .
#查看所有虚悬镜像
#docker image ls -f dangling=true
#删除所有虚悬镜像
#docker image prune
